---
validate#postprocessing:
  _target_: Compose
  transforms:
  - _target_: Activationsd
    keys: pred
    softmax: true
  - _target_: Invertd
    keys:
    - pred
    - label
    transform: "@validate#preprocessing"
    orig_keys: image
    meta_key_postfix: meta_dict
    nearest_interp:
    - false
    - true
    to_tensor: true
  - _target_: AsDiscreted
    keys:
    - pred
    - label
    argmax:
    - true
    - false
    to_onehot: "@output_classes"
  - _target_: CopyItemsd
    keys: "pred"
    times: 1
    names: "pred_save"
  - _target_: AsDiscreted
    keys:
    - pred_save
    argmax:
    - true
  - _target_: SaveImaged
    keys: pred_save
    meta_keys: pred_meta_dict
    output_dir: "@output_dir"
    resample: false
    squeeze_end_dims: true
validate#dataset:
    _target_: CacheDataset
    data: "@val_datalist"
    transform: "@validate#preprocessing"
    cache_rate: 1.0
    num_workers: 4
    copy_cache: false
validate#additional_metrics:
  val_accuracy:
    _target_: ignite.metrics.Accuracy
    output_transform: "$monai.handlers.from_engine(['pred', 'label'])"
  val_mean_iou:
    _target_: MeanIoUHandler
    include_background: false
    output_transform: "$monai.handlers.from_engine(['pred', 'label'])"
  val_confusion_matrix:
    _target_: ConfusionMatrix
    include_background: false
    metric_name:
    - "sensitivity"
    - "specificity"
    - "precision"
    output_transform: "$monai.handlers.from_engine(['pred', 'label'])"
  val_hd:
    _target_: HausdorffDistance
    include_background: false
    output_transform: "$monai.handlers.from_engine(['pred', 'label'])"
  val_surface:
    _target_: SurfaceDistance
    include_background: false
    output_transform: "$monai.handlers.from_engine(['pred', 'label'])"
validate#handlers:
- _target_: CheckpointLoader
  load_path: "$@ckpt_dir + '/model.pt'"
  load_dict:
    model: "@network"
  map_location: cpu
- _target_: StatsHandler
  iteration_log: false
- _target_: MetricsSaver
  save_dir: "@output_dir"
  metrics:
  - val_mean_dice
  - val_acc
  - val_mean_iou
  - val_confusion_matrix
  - val_hd
  - val_surface
  metric_details:
  - val_mean_dice
  - val_mean_iou
  - val_confusion_matrix
  - val_hd
  - val_surface
  batch_transform: "$monai.handlers.from_engine(['image_meta_dict'])"
  summary_ops: "*"
initialize:
- "$setattr(torch.backends.cudnn, 'benchmark', True)"
run:
- "$@validate#evaluator.run()"
